import type { Reward } from "@/types";

const terms = (extra: string[] = []) => [
  "Subject to availability at the selected store.",
  "Cannot be exchanged for cash or transferred.",
  "Ambika Electricals may withdraw the offer at any time.",
  ...extra,
];

export const rewards: Reward[] = [
  // ── Electrical products ────────────────────────────────────────────────
  {
    id: "r-001",
    name: "Philips 9W LED Bulb",
    description: "Energy-efficient LED bulb suitable for everyday home and commercial lighting.",
    type: "Free Electrical Product",
    storeCategory: "Lighting",
    points: 750,
    regularPrice: 120,
    brand: "Philips",
    image: "bulb",
    stockStatus: "In Stock",
    inventory: 140,
    minTier: "Bronze",
    expiryDays: 7,
    status: "Active",
    options: [
      { type: "points", points: 750, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "points_cash", points: 500, cash: 40, label: "Points + Cash", description: "Use fewer points and pay the balance at pickup." },
      { type: "member_price", points: 0, cash: 99, label: "Gold Member Price", description: "Pay the member rate without spending points." },
    ],
    terms: terms(["Valid for 7 days from redemption.", "Maximum 2 redemptions per month.", "Store pickup available."]),
    labels: ["Best for you", "Popular"],
    redemptions: 312,
    createdAt: "2025-03-11",
    maxPerMonth: 2,
  },
  {
    id: "r-002",
    name: "Philips 12W LED Bulb",
    description: "Brighter 12W cool daylight LED bulb with 4kV surge protection.",
    type: "Free Electrical Product",
    storeCategory: "Lighting",
    points: 950,
    regularPrice: 165,
    brand: "Philips",
    image: "bulb",
    stockStatus: "In Stock",
    inventory: 96,
    minTier: "Bronze",
    expiryDays: 7,
    status: "Active",
    options: [
      { type: "points", points: 950, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "points_cash", points: 600, cash: 55, label: "Points + Cash", description: "Use fewer points and pay the balance at pickup." },
    ],
    terms: terms(["Valid for 7 days from redemption.", "Store pickup available."]),
    labels: ["Popular"],
    redemptions: 184,
    createdAt: "2025-03-11",
  },
  {
    id: "r-003",
    name: "Anchor Modular Switch 6A",
    description: "Roma 1-way 6A modular switch with silver alloy contacts.",
    type: "Free Electrical Product",
    storeCategory: "Switches & Sockets",
    points: 850,
    regularPrice: 85,
    brand: "Anchor",
    image: "switch",
    stockStatus: "In Stock",
    inventory: 220,
    minTier: "Bronze",
    expiryDays: 7,
    status: "Active",
    options: [
      { type: "points", points: 850, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "member_price", points: 0, cash: 69, label: "Gold Member Price", description: "Pay the member rate without spending points." },
    ],
    terms: terms(["Valid for 7 days from redemption."]),
    redemptions: 148,
    createdAt: "2025-04-02",
  },
  {
    id: "r-004",
    name: "Anchor 16A Socket",
    description: "3-pin 16A modular socket with child-safe shutter protection.",
    type: "Free Electrical Product",
    storeCategory: "Switches & Sockets",
    points: 1200,
    regularPrice: 145,
    brand: "Anchor",
    image: "socket",
    stockStatus: "In Stock",
    inventory: 130,
    minTier: "Bronze",
    expiryDays: 7,
    status: "Active",
    options: [
      { type: "points", points: 1200, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "points_cash", points: 800, cash: 45, label: "Points + Cash", description: "Use fewer points and pay the balance at pickup." },
    ],
    terms: terms(["Valid for 7 days from redemption."]),
    redemptions: 96,
    createdAt: "2025-04-02",
  },
  {
    id: "r-005",
    name: "Wipro 20W LED Tube Light",
    description: "4-foot LED batten with uniform light spread, ideal for shops and workspaces.",
    type: "Free Electrical Product",
    storeCategory: "Lighting",
    points: 1800,
    regularPrice: 340,
    brand: "Wipro",
    image: "tube",
    stockStatus: "Low Stock",
    inventory: 9,
    minTier: "Silver",
    expiryDays: 10,
    status: "Active",
    options: [
      { type: "points", points: 1800, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "points_cash", points: 1200, cash: 90, label: "Points + Cash", description: "Use fewer points and pay the balance at pickup." },
      { type: "member_price", points: 0, cash: 289, label: "Gold Member Price", description: "Pay the member rate without spending points." },
    ],
    terms: terms(["Available for Silver members and above.", "Valid for 10 days from redemption."]),
    labels: ["Limited"],
    redemptions: 64,
    createdAt: "2025-05-19",
  },
  {
    id: "r-006",
    name: "Anchor Bulb Holder Batten",
    description: "Heat-resistant batten holder for B22 lamps.",
    type: "Free Electrical Product",
    storeCategory: "Accessories",
    points: 300,
    regularPrice: 35,
    brand: "Anchor",
    image: "holder",
    stockStatus: "In Stock",
    inventory: 400,
    minTier: "Bronze",
    expiryDays: 7,
    status: "Active",
    options: [{ type: "points", points: 300, cash: 0, label: "Redeem with Points", description: "Use only your reward points." }],
    terms: terms(["Valid for 7 days from redemption."]),
    redemptions: 402,
    createdAt: "2025-02-08",
  },
  {
    id: "r-007",
    name: "Havells 4 Socket Extension Board",
    description: "4-socket extension board with master switch and 2 metre cord.",
    type: "Free Electrical Product",
    storeCategory: "Accessories",
    points: 1500,
    regularPrice: 690,
    brand: "Havells",
    image: "extension",
    stockStatus: "In Stock",
    inventory: 48,
    minTier: "Silver",
    expiryDays: 14,
    status: "Active",
    options: [
      { type: "points", points: 1500, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "points_cash", points: 1000, cash: 180, label: "Points + Cash", description: "Use fewer points and pay the balance at pickup." },
      { type: "member_price", points: 0, cash: 599, label: "Gold Member Price", description: "Pay the member rate without spending points." },
    ],
    terms: terms(["Available for Silver members and above.", "Valid for 14 days from redemption."]),
    labels: ["Member Exclusive"],
    redemptions: 71,
    createdAt: "2025-06-04",
  },
  {
    id: "r-008",
    name: "Electrical Insulation Tape (Pack of 5)",
    description: "PVC insulation tape, 5-roll multi-colour pack.",
    type: "Free Electrical Product",
    storeCategory: "Accessories",
    points: 250,
    regularPrice: 130,
    brand: "Anchor",
    image: "tape",
    stockStatus: "In Stock",
    inventory: 260,
    minTier: "Bronze",
    expiryDays: 7,
    status: "Active",
    options: [{ type: "points", points: 250, cash: 0, label: "Redeem with Points", description: "Use only your reward points." }],
    terms: terms(["Valid for 7 days from redemption."]),
    labels: ["Popular"],
    redemptions: 520,
    createdAt: "2025-01-14",
  },
  {
    id: "r-009",
    name: "PVC Conduit Pack (10 lengths)",
    description: "ISI marked 20mm rigid PVC conduit, pack of 10 three-metre lengths.",
    type: "Free Electrical Product",
    storeCategory: "Accessories",
    points: 700,
    regularPrice: 450,
    brand: "Polycab",
    image: "conduit",
    stockStatus: "In Stock",
    inventory: 84,
    minTier: "Bronze",
    expiryDays: 10,
    status: "Active",
    options: [
      { type: "points", points: 700, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "points_cash", points: 450, cash: 120, label: "Points + Cash", description: "Use fewer points and pay the balance at pickup." },
    ],
    terms: terms(["Valid for 10 days from redemption."]),
    redemptions: 58,
    createdAt: "2025-05-02",
  },
  {
    id: "r-010",
    name: "Cable Tie Pack (100 pcs)",
    description: "Nylon self-locking cable ties, 200mm, pack of 100.",
    type: "Free Electrical Product",
    storeCategory: "Accessories",
    points: 350,
    regularPrice: 120,
    brand: "Anchor",
    image: "tie",
    stockStatus: "In Stock",
    inventory: 180,
    minTier: "Bronze",
    expiryDays: 7,
    status: "Active",
    options: [{ type: "points", points: 350, cash: 0, label: "Redeem with Points", description: "Use only your reward points." }],
    terms: terms(["Valid for 7 days from redemption."]),
    redemptions: 143,
    createdAt: "2025-02-20",
  },
  {
    id: "r-011",
    name: "Anchor Fan Regulator",
    description: "5-step modular fan regulator with low heat dissipation.",
    type: "Free Electrical Product",
    storeCategory: "Fans",
    points: 1100,
    regularPrice: 310,
    brand: "Anchor",
    image: "regulator",
    stockStatus: "In Stock",
    inventory: 62,
    minTier: "Bronze",
    expiryDays: 10,
    status: "Active",
    options: [
      { type: "points", points: 1100, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "points_cash", points: 700, cash: 60, label: "Points + Cash", description: "Use fewer points and pay the balance at pickup." },
    ],
    terms: terms(["Valid for 10 days from redemption."]),
    redemptions: 84,
    createdAt: "2025-04-27",
  },
  {
    id: "r-012",
    name: "Philips Smart Wi-Fi LED Bulb",
    description: "16 million colours, app and voice controlled smart LED bulb.",
    type: "Free Electrical Product",
    storeCategory: "Lighting",
    points: 2500,
    regularPrice: 999,
    brand: "Philips",
    image: "smartbulb",
    stockStatus: "Low Stock",
    inventory: 7,
    minTier: "Gold",
    expiryDays: 14,
    status: "Active",
    options: [
      { type: "points", points: 2500, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "points_cash", points: 2000, cash: 150, label: "Points + Cash", description: "Use fewer points and pay the balance at pickup." },
      { type: "member_price", points: 0, cash: 849, label: "Gold Member Price", description: "Pay the member rate without spending points." },
    ],
    terms: terms(["Gold members and above only.", "Valid for 14 days from redemption.", "One redemption per month."]),
    labels: ["Member Exclusive", "New"],
    redemptions: 41,
    createdAt: "2025-08-01",
    maxPerMonth: 1,
  },
  {
    id: "r-013",
    name: "Crompton Ceiling Fan 1200mm",
    description: "High-speed 1200mm ceiling fan with dust-resistant finish.",
    type: "Free Electrical Product",
    storeCategory: "Fans",
    points: 8000,
    regularPrice: 2450,
    brand: "Crompton",
    image: "fan",
    stockStatus: "In Stock",
    inventory: 18,
    minTier: "Silver",
    expiryDays: 21,
    status: "Active",
    options: [
      { type: "points", points: 8000, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "points_cash", points: 2000, cash: 1650, label: "Points + Cash", description: "Use fewer points and pay the balance at pickup." },
      { type: "member_price", points: 0, cash: 2199, label: "Gold Member Price", description: "Pay the member rate without spending points." },
    ],
    terms: terms(["Valid for 21 days from redemption.", "Installation not included."]),
    labels: ["Limited"],
    redemptions: 22,
    createdAt: "2025-07-12",
  },
  {
    id: "r-014",
    name: "Schneider 32A MCB",
    description: "C-curve miniature circuit breaker with 10kA breaking capacity.",
    type: "Free Electrical Product",
    storeCategory: "Protection",
    points: 2600,
    regularPrice: 380,
    brand: "Schneider Electric",
    image: "mcb",
    stockStatus: "In Stock",
    inventory: 54,
    minTier: "Silver",
    expiryDays: 14,
    status: "Active",
    options: [
      { type: "points", points: 2600, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "points_cash", points: 1500, cash: 170, label: "Points + Cash", description: "Use fewer points and pay the balance at pickup." },
    ],
    terms: terms(["Available for Silver members and above."]),
    redemptions: 37,
    createdAt: "2025-06-22",
  },
  {
    id: "r-015",
    name: "Polycab 1.5 sq mm FR Wire Coil",
    description: "Flame retardant copper house wire, 90 metre coil.",
    type: "Free Electrical Product",
    storeCategory: "Wires & Cables",
    points: 9500,
    regularPrice: 1450,
    brand: "Polycab",
    image: "wire",
    stockStatus: "In Stock",
    inventory: 26,
    minTier: "Gold",
    expiryDays: 21,
    status: "Active",
    options: [
      { type: "points", points: 9500, cash: 0, label: "Redeem with Points", description: "Use only your reward points." },
      { type: "points_cash", points: 3000, cash: 990, label: "Points + Cash", description: "Use fewer points and pay the balance at pickup." },
      { type: "member_price", points: 0, cash: 1299, label: "Gold Member Price", description: "Pay the member rate without spending points." },
    ],
    terms: terms(["Gold members and above only.", "Valid for 21 days from redemption."]),
    labels: ["Member Exclusive"],
    redemptions: 15,
    createdAt: "2025-07-30",
  },

  // ── Discounts / coupons / offers ───────────────────────────────────────
  {
    id: "r-101",
    name: "₹100 OFF Electrical Purchase",
    description: "Flat ₹100 off on your next electrical purchase of ₹800 or more.",
    type: "Discount",
    storeCategory: "Discounts",
    points: 900,
    regularPrice: 100,
    image: "coupon",
    stockStatus: "In Stock",
    inventory: 999,
    minTier: "Bronze",
    expiryDays: 30,
    minPurchase: 800,
    status: "Active",
    options: [{ type: "coupon", points: 900, cash: 0, label: "Redeem Coupon", description: "Get a coupon code to use at checkout." }],
    terms: terms(["Minimum purchase of ₹800.", "One coupon per bill.", "Valid for 30 days."]),
    labels: ["Popular", "Best for you"],
    redemptions: 486,
    createdAt: "2025-01-05",
  },
  {
    id: "r-102",
    name: "₹250 OFF Electrical Purchase",
    description: "Flat ₹250 off on electrical purchases of ₹2,000 or more.",
    type: "Discount",
    storeCategory: "Discounts",
    points: 2000,
    regularPrice: 250,
    image: "coupon",
    stockStatus: "In Stock",
    inventory: 999,
    minTier: "Bronze",
    expiryDays: 30,
    minPurchase: 2000,
    status: "Active",
    options: [{ type: "coupon", points: 2000, cash: 0, label: "Redeem Coupon", description: "Get a coupon code to use at checkout." }],
    terms: terms(["Minimum purchase of ₹2,000.", "Valid for 30 days."]),
    redemptions: 231,
    createdAt: "2025-01-05",
  },
  {
    id: "r-103",
    name: "₹500 OFF Electrical Purchase",
    description: "Flat ₹500 off on electrical purchases of ₹5,000 or more.",
    type: "Discount",
    storeCategory: "Discounts",
    points: 4000,
    regularPrice: 500,
    image: "coupon",
    stockStatus: "In Stock",
    inventory: 999,
    minTier: "Silver",
    expiryDays: 30,
    minPurchase: 5000,
    status: "Active",
    options: [{ type: "coupon", points: 4000, cash: 0, label: "Redeem Coupon", description: "Get a coupon code to use at checkout." }],
    terms: terms(["Minimum purchase of ₹5,000.", "Silver members and above."]),
    redemptions: 118,
    createdAt: "2025-02-16",
  },
  {
    id: "r-104",
    name: "10% OFF Electrical Accessories",
    description: "Save 10% on holders, conduits, tapes, glands and all wiring accessories.",
    type: "Coupon",
    storeCategory: "Coupons",
    points: 1500,
    regularPrice: 300,
    image: "coupon",
    stockStatus: "In Stock",
    inventory: 999,
    minTier: "Bronze",
    expiryDays: 21,
    status: "Active",
    options: [{ type: "coupon", points: 1500, cash: 0, label: "Redeem Coupon", description: "Get a coupon code to use at checkout." }],
    terms: terms(["Applies to the Accessories category only.", "Maximum discount ₹500."]),
    labels: ["Popular"],
    redemptions: 264,
    createdAt: "2025-03-28",
  },
  {
    id: "r-105",
    name: "Free Cable Cutting & Home Delivery",
    description: "Complimentary cable cutting plus free same-city delivery on your next wire purchase.",
    type: "Special Offer",
    storeCategory: "Special Offers",
    points: 1200,
    regularPrice: 250,
    image: "offer",
    stockStatus: "In Stock",
    inventory: 200,
    minTier: "Silver",
    expiryDays: 30,
    status: "Active",
    options: [{ type: "coupon", points: 1200, cash: 0, label: "Redeem Offer", description: "Get a code to use with your next wire order." }],
    terms: terms(["Silver members and above.", "Delivery within Surat city limits."]),
    labels: ["New"],
    redemptions: 47,
    createdAt: "2025-08-11",
  },
  {
    id: "r-106",
    name: "Festival Wiring Bundle Offer",
    description: "20% off when you buy any wire coil with a distribution box.",
    type: "Special Offer",
    storeCategory: "Special Offers",
    points: 3000,
    regularPrice: 900,
    image: "offer",
    stockStatus: "In Stock",
    inventory: 120,
    minTier: "Gold",
    expiryDays: 30,
    status: "Active",
    options: [{ type: "coupon", points: 3000, cash: 0, label: "Redeem Offer", description: "Get a code to use with your bundle purchase." }],
    terms: terms(["Gold members and above.", "Applies to a single combined bill."]),
    labels: ["Member Exclusive"],
    redemptions: 29,
    createdAt: "2025-08-19",
  },
];

export const rewardById = (id: string) => rewards.find((r) => r.id === id);
